name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Swagger UI for Todo App
        uses: Legion2/swagger-ui-action@v1
        with:
          output: public/todo-app
          spec-file: ./todo-app/openapi.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Swagger UI for Tickets API
        uses: Legion2/swagger-ui-action@v1
        with:
          output: public/tickets
          spec-file: ./tickets/openapi.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true
